Rbh 66 user page
Roommate-Budget-Helper/budget-helper-full-stack-app pull request #20
Opened 2023-04-24 18:45 UTC by DavidPurdy1

## Jira Ticket:
[RBH-66](https://roommatebudgethelper.atlassian.net/jira/software/projects/RBH/boards/1?selectedIssue=RBH-66)
## Description of Work
Added a user page with ability to add profile picture, signout, and set payment links for emails in the future. Notification settings for emails will also go here eventually. 
## Acceptance Criteria

- Add image and see if image appears above
- Edit Image and make verify image changes
- Verify that images look correct on billing and charging screens
- Add payment method, verify that payment method persists on refresh
- Change payment methods
- Sign out and verify that the user cannot access any pages

## How to Test

- Run e2e Cypress tests

### List of Changes:

- Changed how images look on screens showing image
- Return the signed url on queries, but store only the key
- Added 3 spots to store payment methods in the schema
- Page to set these options
- Sign out button 
- Future spot for the email notifications once that is set up

### Screenshots

| Image | Description |
| ![image](https://user-images.githubusercontent.com/56805345/234086680-cf636f44-0c19-47e4-bd64-2a70b19091cf.png) | Top of page |
| ![image](https://user-images.githubusercontent.com/56805345/234086754-04767648-002b-4d31-8219-ac93d5a097d2.png) |
Bottom of Page |

2023-04-24 19:06 UTC, rhit-daviscl requested changes
The JavaScript test failed. Needs the changes the test says to make

2023-04-24 20:05 UTC, rhit-daviscl requested changes
![image](https://user-images.githubusercontent.com/73263545/234104114-5d20496e-d1c6-4284-8534-55d29a6a93bc.png)
Whenever I try to update payment methods. I do not have any input fields.

2023-04-26 05:06 UTC, RealJasomo commented on app/src/pages/user.tsx
> +        // TODO: Set notification settings for email here
Yeah let's do this as a separate task

2023-04-26 05:07 UTC, RealJasomo approved these changes
looks good, we can optimize the image loading here but we can do that as a separate issue

2023-05-02 00:53 UTC, DavidPurdy1 commented
> ![image](https://user-images.githubusercontent.com/73263545/234104114-5d20496e-d1c6-4284-8534-55d29a6a93bc.png) Whenever I try to update payment methods. I do not have any input fields.

I haven't been able to recreate this issue. I am guessing that you might not have updated the schema/db. If you can try that when you have some time and let me know @rhit-daviscl

2023-05-02 01:16 UTC, rhit-daviscl approved these changes

2023-05-02 02:15 UTC, merged